name: CI
on:
  pull_request:
    branches: [main]
jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    needs: generateTOC
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npx awesome-lint
